/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__pointer2ndarray
#define __PYX_HAVE__pointer2ndarray


#ifndef __PYX_HAVE_API__pointer2ndarray

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *tonumpyarray(double *, PY_LONG_LONG);

#endif /* !__PYX_HAVE_API__pointer2ndarray */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpointer2ndarray(void);
#else
PyMODINIT_FUNC PyInit_pointer2ndarray(void);
#endif

#endif /* !__PYX_HAVE__pointer2ndarray */
